// <auto-generated />
namespace DivineAcademy.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CourseName_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseName_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202203211206233_CourseName_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
